### PR TITLE
Resiliancy to unlink failures during cleanup and support for data download behind a proxy

### PR DESCRIPTION
**Pull request by chapmanb**
Thank you for Battenberg. We've been working on integrating it into bcbio (https://github.com/chapmanb/bcbio-nextgen) and have been using it with good success to estimate normal contamination. I ran into a couple of small issues during data preparation and in production runs that this pull request addresses:

- It provides an option to use curl for data download. I could not make `File::Fetch` work behind a proxy, but curl works cleanly and provides a useful alternative for folks who don't mind the external dependency.
- It avoids failing when unable to unlink a file during a re-run of a partially finished analysis. Battenberg can occasionally end up in a state where a file it wants to unlink is already removed, and this avoids dying when this happens.

Thanks again for your work on this. Please let me know if you need any other details.

### CODE REVIEW

**Comment by chapmanb** [comment]
As I've worked with Battenberg more, this pull request collected two additional fixes to allow support for hg19 (chr-prefixed) references. I tried naively feeding hg19 BAMs with the standard Battenberg data files, but that ends up with empty alleleFrequency counts. So I prepared a small script that will convert over the Battenberg downloads for hg19 naming:

https://github.com/chapmanb/cloudbiolinux/blob/49af62ac413ce4c18f9f3d82327b66416f85ee91/ggd-recipes/hg19/battenberg.yaml#L24

Then it runs with two fixes:

- Explicitly pass in the chromosome names to ascat instead of assuming 1-22 + X.
- Remove code that strips off chr-prefixes and left empty matrices, to use the inputs as is.

This lets is run cleanly with both GRCh37 and hg19-style naming.

I'm happy to split these into separate PRs or otherwise submit them in whatever the best way is that works for you. Thanks again for Battenberg.

**Comment by keiranmraine** [comment]
Hi, Thanks for this, I'll need to get the statistician responsible for the R code to review your changes before this can be merged but this looks good to me.

@sdentro do you have some time to look at this?  There's some conflicts which I'm guessing will be due to your recent fixes.

**Comment by sdentro** [comment]
Yes, will look into this.

On 24/11/2015 05:45, Keiran Raine wrote:
>
> Hi, Thanks for this, I'll need to get the statistician responsible for 
> the R code to review your changes before this can be merged but this 
> looks good to me.
>
> @sdentro <https://github.com/sdentro> do you have some time to look at 
> this? There's some conflicts which I'm guessing will be due to your 
> recent fixes.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cancerit/cgpBattenberg/pull/17#issuecomment-159155197>.
>




-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by chapmanb** [comment]
Keiran and Stefan;
Thanks much for the interest in these. I'm definitely willing to help however I can with getting in the fixes for installation and generalized non-hg19 naming. I know things have gotten a little out of sync as you've continued development so can look into adjusting parts that need to get in. Thanks much.

**Comment by ohofmann** [comment]
We'd love to use Battenberg for the cancer components of the Scottish Genome Partnership; since we are using bcbio for all data processing it would be good to see these changes going in. Is there any way to help or update the pull request to make this happen?

**Comment by sdentro** [comment]
Am in the process of testing bugfixes applied the last couple of months across the failed samples I have locally. Will merge this pull request next.

**Comment by sdentro** [comment]
Changes have been merged and tested. Thank you very much @chapmanb

**Comment by chapmanb** [comment]
Stefan -- awesome, thanks so much for looking at these and merging them in. All the work on Battenberg is much appreciated.

**Pull request merged**
