### PR TITLE
Release/3.5.0

### PR DESCRIPTION
**Pull request by drjsanger**

### CODE REVIEW

**Comment by keiranmraine** [comment]
@drjsanger, can I just check, are all the changes in the perl code, nothing in the R?

**Comment by drjsanger** [comment]
@kr2 R changes are here in CASMIT fork of battenberg R code https://github.com/cancerit/battenberg/tree/feature/grch38
Need to decide if we keep in a feature branch then PR to original repository or we merge on our side.

**Comment by keiranmraine** [comment]
> @keiranmraine R changes are here in CASMIT fork of battenberg R code https://github.com/cancerit/battenberg/tree/feature/grch38
> Need to decide if we keep in a feature branch then PR to original repository or we merge on our side.

We can create a tag from the feature branch in our fork in the short term, or even pull by commit ID from our fork.

**Comment by drjsanger** [comment]
Done https://github.com/cancerit/battenberg/releases/tag/v2.3.0

**Pull request merged**
